# Generated by Django 5.2.2 on 2025-06-29 05:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=150, null=True),
        ),
    ]
